AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AutoScalingTerminationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.12
      Timeout: 30
  ConnectivityTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.connectivity_test_handler
      Runtime: python3.12
      Timeout: 30
